### ISSUE TITLE
Compiler issue

### ISSUE THREAD

**Issue by Anard** [k-o-d-e-n/CGLayout#2]
Hi,

I don't know if you still use this framework, but I can't compile it in XCode :
In private.cglayout.swift, lines 62 && 66, compiler doesn't accept the syncGuard syntax :
> Ambiguous use of 'syncGuard(mainThread:)'

I don't know how to solve it...

**Comment by k-o-d-e-n** [comment]
Hi,
Yeah, unfortunately, framework is not in active development.
I pushed last changes. Try it compile again.

**Comment by Anard** [comment]
Thanks, it seems to compile now ;)
Trying to get working an autolayout view controller for raspi. Hope it'll be OK.
Thanks for your work.

**Comment by k-o-d-e-n** [comment]
If there are other questions, I am ready to answer.
Good coding!
